import Fastify from 'fastify';import cors from '@fastify/cors';import helmet from '@fastify/helmet';import rateLimit from '@fastify/rate-limit';import jwt from '@fastify/jwt';import {Server} from 'socket.io';import {PrismaClient} from '@prisma/client';import {compare} from 'bcryptjs';import {createRoomSchema,joinRoomSchema,settingsSchema,answerSchema,voteSchema} from '@esmfamil/shared';import {normalizePersian} from '@esmfamil/persian-text';import {RoomEngine,token,tokenHash} from './room-engine.js';
import {finalizeRound} from './finalize-round.js';
import {recalculateResults} from './finalize-round.js';
import {chooseLetter} from './letter-selection.js';
const db=new PrismaClient(),app=Fastify({logger:{redact:['req.headers.authorization','req.body.inviteToken','req.body.sessionToken']}}),engine=new RoomEngine();
await app.register(cors,{origin:process.env.WEB_ORIGIN?.split(',')??['http://localhost:5173'],credentials:true});await app.register(helmet);await app.register(rateLimit,{max:120,timeWindow:'1 minute'});await app.register(jwt,{secret:process.env.JWT_SECRET??'development-only-secret-change-me-32'});
app.get('/health',()=>({ok:true}));app.get('/api/categories',()=>db.category.findMany({where:{active:true},orderBy:{name:'asc'}}));
app.post('/api/rooms',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(req,reply)=>{const x=createRoomSchema.parse(req.body),invite=token(),session=token();const room=await db.room.create({data:{inviteTokenHash:tokenHash(invite),players:{create:{displayName:x.displayName,normalizedName:normalizePersian(x.displayName).normalizedText,sessionTokenHash:tokenHash(session),isHost:true}}},include:{players:true}});const host=room.players[0]!;engine.create(room.id,{id:host.id,name:host.displayName,host:true,ready:false,connected:true,answers:{}});return reply.code(201).send({roomId:room.id,inviteToken:invite,sessionToken:session,playerId:host.id,inviteUrl:`/join/${room.id}?token=${invite}`})});
app.post('/api/rooms/:roomId/join',{config:{rateLimit:{max:20,timeWindow:'1 minute'}}},async(req:any,reply)=>{const x=joinRoomSchema.parse(req.body),row=await db.room.findUnique({where:{id:req.params.roomId},include:{players:true}});if(!row||row.inviteTokenHash!==tokenHash(x.inviteToken))return reply.code(403).send({message:'لینک دعوت معتبر نیست.'});if(row.status!=='LOBBY'||row.players.length>=8)return reply.code(409).send({message:row.players.length>=8?'اتاق پر است.':'بازی شروع شده است.'});const session=token();try{const p=await db.player.create({data:{roomId:row.id,displayName:x.displayName,normalizedName:normalizePersian(x.displayName).normalizedText,sessionTokenHash:tokenHash(session)}});let runtime=engine.rooms.get(row.id);if(!runtime){const host=row.players.find(p=>p.isHost)!;runtime=engine.create(row.id,{id:host.id,name:host.displayName,host:true,ready:host.isReady,connected:true,answers:{}});for(const old of row.players.filter(p=>p.id!==host.id))engine.join(runtime,{id:old.id,name:old.displayName,host:false,ready:old.isReady,connected:true,answers:{}})}engine.join(runtime,{id:p.id,name:p.displayName,host:false,ready:false,connected:true,answers:{}});io.to(row.id).emit('room:state',runtime);return {sessionToken:session,playerId:p.id,roomId:row.id}}catch{return reply.code(409).send({message:'این نام در اتاق استفاده شده است.'})}});
app.post('/api/admin/login',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req:any,reply)=>{const {email,password}=req.body??{},admin=await db.admin.findUnique({where:{email}});if(!admin||!await compare(password,admin.passwordHash))return reply.code(401).send({message:'اطلاعات ورود نادرست است.'});return {token:app.jwt.sign({sub:admin.id,role:'admin'},{expiresIn:'2h'})}});
const adminGuard=async(req:any,reply:any)=>{try{await req.jwtVerify()}catch{return reply.code(401).send({message:'نیاز به ورود مدیر است.'})}};
app.get('/api/admin/dashboard',{preHandler:adminGuard},async()=>{const [terms,aliases,rejected,queue,games,rounds]=await Promise.all([db.term.count({where:{active:true}}),db.termAlias.count(),db.rejectedAnswer.count({where:{active:true}}),db.moderationQueueItem.count({where:{status:'PENDING'}}),db.game.count(),db.round.count()]);return {terms,aliases,rejected,queue,games,rounds}});
app.get('/api/admin/unknowns',{preHandler:adminGuard},()=>db.moderationQueueItem.findMany({include:{category:true,events:true},orderBy:{useCount:'desc'}}));
app.post('/api/admin/unknowns/:id/decide',{preHandler:adminGuard},async(req:any)=>{const {action,note}=req.body,item=await db.moderationQueueItem.findUniqueOrThrow({where:{id:req.params.id}});const status=action==='APPROVE'?'APPROVED':'REJECTED';return db.$transaction(async tx=>{if(action==='APPROVE'){const term=await tx.term.upsert({where:{normalized:item.normalizedText},update:{active:true},create:{canonical:item.originalText,normalized:item.normalizedText,initialLetter:item.letter,source:'admin',confidence:1}});await tx.termCategory.upsert({where:{termId_categoryId:{termId:term.id,categoryId:item.categoryId}},update:{},create:{termId:term.id,categoryId:item.categoryId}})}else await tx.rejectedAnswer.upsert({where:{normalized_categoryId:{normalized:item.normalizedText,categoryId:item.categoryId}},update:{active:true,reason:'WRONG_CATEGORY'},create:{normalized:item.normalizedText,categoryId:item.categoryId,scope:'CATEGORY',reason:'WRONG_CATEGORY',reasonFa:note??'رد مدیر'}});await tx.moderationEvent.create({data:{itemId:item.id,action,before:{status:item.status},after:{status},note}});return tx.moderationQueueItem.update({where:{id:item.id},data:{status}})})});
const io=new Server(app.server,{cors:{origin:process.env.WEB_ORIGIN?.split(',')??['http://localhost:5173']}});
function beginVoting(r:import('./room-engine.js').RuntimeRoom){const unknown=new Map<string,{text:string;categoryId:string;ownerIds:string[]}>();for(const result of r.results?.players??[])for(const cell of result.cells)if(cell.status==='UNKNOWN'){const key=`${cell.categoryId}:${normalizePersian(cell.text).normalizedText}`;const item=unknown.get(key)??{text:cell.text,categoryId:cell.categoryId,ownerIds:[]};item.ownerIds.push(result.playerId);unknown.set(key,item)}r.voteQueue=[...unknown.values()].map(item=>({...item,id:token(),endsAt:0,votes:{}}));if(!r.settings.votingEnabled||!r.voteQueue.length){r.state='RESULTS';io.to(r.id).emit('room:state',r);return}r.state='VOTING';advanceVote(r)}
function advanceVote(r:import('./room-engine.js').RuntimeRoom){const vote=r.voteQueue?.shift();if(!vote){delete r.currentVote;recalculateResults(r);r.state='RESULTS';io.to(r.id).emit('room:state',r);return}vote.endsAt=Date.now()+10_000;r.currentVote=vote;io.to(r.id).emit('room:state',r);setTimeout(()=>resolveVoteQuestion(r.id,vote.id),10_000)}
function resolveVoteQuestion(roomId:string,voteId:string){const r=engine.rooms.get(roomId),vote=r?.currentVote;if(!r||r.state!=='VOTING'||!vote||vote.id!==voteId)return;const eligible=Object.entries(vote.votes).filter(([id,choice])=>!vote.ownerIds.includes(id)&&r.players.some(p=>p.id===id&&p.connected)&&choice!=='UNSURE');const yes=eligible.filter(([,choice])=>choice==='VALID').length,no=eligible.filter(([,choice])=>choice==='INVALID').length;const accepted=eligible.length>=2&&yes>no;if(accepted)for(const result of r.results?.players??[])for(const cell of result.cells)if(cell.categoryId===vote.categoryId&&normalizePersian(cell.text).normalizedText===normalizePersian(vote.text).normalizedText){cell.status='VALID';cell.reasonFa='با رأی اکثریت بازیکنان برای این دور پذیرفته شد.'}advanceVote(r)}
io.use(async(socket,next)=>{const {roomId,playerId,sessionToken}=socket.handshake.auth;const p=await db.player.findFirst({where:{id:playerId,roomId,sessionTokenHash:tokenHash(sessionToken??'')}});if(!p)return next(new Error('UNAUTHORIZED'));socket.data={roomId,playerId};next()});
io.on('connection',socket=>{const {roomId,playerId}=socket.data;socket.join(roomId);const room=engine.rooms.get(roomId);const player=room?.players.find(p=>p.id===playerId);if(player)player.connected=true;if(room)io.to(roomId).emit('room:state',room);
 socket.on('player:ready',()=>{const r=engine.rooms.get(roomId),p=r?.players.find(x=>x.id===playerId);if(p){p.ready=!p.ready;io.to(roomId).emit('room:state',r)}});
 socket.on('settings:update',(raw,ack)=>{try{const s=settingsSchema.parse(raw),r=engine.rooms.get(roomId),p=r?.players.find(x=>x.id===playerId);if(!r||!p?.host||r.state!=='LOBBY')throw Error('FORBIDDEN');r.settings=s;io.to(roomId).emit('room:state',r);ack?.({ok:true})}catch(error){app.log.error({error},'settings update failed');ack?.({ok:false,message:error instanceof Error?error.message:'UNKNOWN'})}});
 socket.on('game:start',async(_:unknown,ack)=>{const r=engine.rooms.get(roomId),p=r?.players.find(x=>x.id===playerId);if(!r||!p?.host||r.players.length<2||r.settings.categoryIds.length<5)return ack?.({ok:false,message:'حداقل ۲ بازیکن و ۵ موضوع لازم است.'});try{const letter=await chooseLetter(db,r);r.state='COUNTDOWN';r.round={id:token(),number:1,letter,startsAt:Date.now()+3000,endsAt:Date.now()+3000+r.settings.durationSeconds*1000};io.to(roomId).emit('room:state',r);setTimeout(()=>{if(r.state==='COUNTDOWN'){r.state='PLAYING';io.to(roomId).emit('room:state',r)}},3000);ack?.({ok:true})}catch{ack?.({ok:false,message:'برای موضوع‌های انتخاب‌شده حرف قابل‌بازی پیدا نشد.'})}});
 socket.on('answer:save',(raw,ack)=>{try{const x=answerSchema.parse(raw),r=engine.rooms.get(roomId),p=r?.players.find(x=>x.id===playerId);if(!r||!p||r.state!=='PLAYING'||r.round?.id!==x.roundId)throw Error();p.answers[x.categoryId]=x.text;ack?.({ok:true})}catch{ack?.({ok:false})}});
 socket.on('round:stop',(_:unknown,ack)=>{const r=engine.rooms.get(roomId);const ok=!!r&&engine.reserveStop(r,playerId);if(ok)io.to(roomId).emit('room:state',r);ack?.({ok})});
 socket.on('round:confirm',async(_:unknown,ack)=>{const r=engine.rooms.get(roomId),ok=!!r&&engine.confirmStop(r,playerId);if(!r||!ok)return ack?.({ok:false});io.to(roomId).emit('room:state',r);try{r.state='VALIDATING';io.to(roomId).emit('room:state',r);r.results=await finalizeRound(db,r);beginVoting(r);ack?.({ok:true})}catch(error){app.log.error({error},'round finalization failed');r.state='RESULTS';io.to(roomId).emit('room:state',r);ack?.({ok:false})}});
 socket.on('round:next',async(_:unknown,ack)=>{const r=engine.rooms.get(roomId),p=r?.players.find(x=>x.id===playerId);if(!r||!p?.host||r.state!=='RESULTS'||!r.round)return ack?.({ok:false});if(r.round.number>=r.settings.roundCount){r.state='FINISHED';io.to(roomId).emit('room:state',r);return ack?.({ok:true})}try{const number=r.round.number+1,letter=await chooseLetter(db,r);r.players.forEach(x=>{x.answers={};x.ready=false});delete r.results;r.state='COUNTDOWN';r.round={id:token(),number,letter,startsAt:Date.now()+3000,endsAt:Date.now()+3000+r.settings.durationSeconds*1000};io.to(roomId).emit('room:state',r);setTimeout(()=>{if(r.state==='COUNTDOWN'){r.state='PLAYING';io.to(roomId).emit('room:state',r)}},3000);ack?.({ok:true})}catch{ack?.({ok:false})}});
 socket.on('vote:cast',(raw,ack)=>{try{const x=voteSchema.parse(raw),r=engine.rooms.get(roomId),vote=r?.currentVote;if(!r||r.state!=='VOTING'||!vote||vote.id!==x.voteSessionId||Date.now()>vote.endsAt||vote.votes[playerId])throw Error();vote.votes[playerId]=x.choice;ack?.({ok:true})}catch{ack?.({ok:false})}});socket.on('disconnect',()=>{const r=engine.rooms.get(roomId),p=r?.players.find(x=>x.id===playerId);if(p)p.connected=false;if(r && r.round && r.round.stopperId===playerId&&r.state==='STOP_CONFIRMATION'){r.state='PLAYING';delete r.round.stopperId}if(r)io.to(roomId).emit('room:state',r)})});
const port=Number(process.env.PORT??3001);const shutdown=async()=>{io.close();await app.close();await db.$disconnect()};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);await app.listen({port,host:'0.0.0.0'});
