import React,{useEffect,useRef,useState} from 'react';import{createRoot}from'react-dom/client';import{io,Socket}from'socket.io-client';import'./style.css';
const API=import.meta.env.VITE_API_URL??'';
type Category={id:string;name:string;description:string};
type Cell={categoryId:string;text:string;status:string;reasonFa:string;points:number};
type Player={id:string;name:string;host:boolean;ready:boolean;connected:boolean;answers:Record<string,string>};
type Room={id:string;state:string;players:Player[];settings:{durationSeconds:number;roundCount:number;categoryIds:string[];votingEnabled:boolean;difficulty:string};round?:{id:string;number:number;letter:string;startsAt:number;endsAt:number;stopperId?:string};currentVote?:{id:string;text:string;categoryId:string;endsAt:number};results?:{stopperId?:string;players:{playerId:string;name:string;roundScore:number;totalScore:number;cells:Cell[]}[]}};
const store=(k:string,v:string)=>localStorage.setItem(k,v);
const request=async(path:string,options?:RequestInit)=>{const r=await fetch(API+path,{...options,headers:{'content-type':'application/json',...options?.headers}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error((j as any).message??'خطایی رخ داد');return j};
const difficultyLabels:Record<string,string>={EASY:'آسان',MEDIUM:'متوسط',HARD:'سخت',MIXED:'ترکیبی'};

function Home(){const[name,setName]=useState('');const[error,setError]=useState('');const create=async()=>{try{const x=await request('/api/rooms',{method:'POST',body:JSON.stringify({displayName:name})});Object.entries(x).forEach(([k,v])=>store(k,String(v)));location.href=`/room/${(x as any).roomId}`}catch(e){setError((e as Error).message)}};return <main className="landing"><section className="hero"><span className="badge">بازی دورهمی، این بار آنلاین</span><h1>اسم‌فامیل<span>؛ سریع، منصفانه، زنده</span></h1><p>اتاق خصوصی بساز، دوستانت را دعوت کن و داوری را به موتور فارسی ما بسپار.</p><div className="create"><label>نام نمایشی<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً سارا" maxLength={24}/></label><button onClick={create} disabled={name.trim().length<2}>ساخت اتاق</button></div>{error&&<p className="error" role="alert">{error}</p>}<div className="features"><article>⚡<b>هم‌زمان</b><small>تایمر دقیق سرور</small></article><article>🛡️<b>داوری منصفانه</b><small>واژه‌نامه و رأی گروهی</small></article><article>🔗<b>کاملاً خصوصی</b><small>فقط با لینک دعوت</small></article></div></section></main>}

function Join({roomId}:{roomId:string}){const[name,setName]=useState('');const[error,setError]=useState('');const invite=new URLSearchParams(location.search).get('token')??'';const join=async()=>{try{const x=await request(`/api/rooms/${roomId}/join`,{method:'POST',body:JSON.stringify({displayName:name,inviteToken:invite})});Object.entries(x).forEach(([k,v])=>store(k,String(v)));location.href=`/room/${roomId}`}catch(e){setError((e as Error).message)}};return <main className="center"><section className="card"><h1>ورود به اتاق 🎲</h1><p>دوستانت منتظرند؛ با چه نامی صدایت کنند؟</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="نام نمایشی" maxLength={24}/><button onClick={join} disabled={name.trim().length<2}>پیوستن به بازی</button>{error&&<p className="error">{error}</p>}</section></main>}

function RoomPage({roomId}:{roomId:string}){
 const[room,setRoom]=useState<Room>();const[cats,setCats]=useState<Category[]>([]);const[socket,setSocket]=useState<Socket>();const[tick,setTick]=useState(Date.now());const[voted,setVoted]=useState(false);const me=localStorage.playerId;const saveTimers=useRef<Record<string,ReturnType<typeof setTimeout>>>({});
 useEffect(()=>{request('/api/categories').then(v=>setCats(v as Category[]));const s=io(API,{auth:{roomId,playerId:me,sessionToken:localStorage.sessionToken}});s.on('room:state',setRoom);s.on('connect_error',()=>{});setSocket(s);const t=setInterval(()=>setTick(Date.now()),250);return()=>{s.close();clearInterval(t)}},[]);
 useEffect(()=>setVoted(false),[room?.currentVote?.id]);
 if(!room)return <main className="center"><div className="loader">در حال اتصال به اتاق…</div></main>;
 const mine=room.players.find(p=>p.id===me),host=mine?.host;const catName=(id:string)=>cats.find(c=>c.id===id)?.name??id;
 const share=async()=>{const invitePath=localStorage.inviteUrl;if(!invitePath){alert('لینک دعوت فقط برای میزبان در دسترس است.');return}const link=location.origin+invitePath;try{if(!navigator.clipboard)throw new Error('CLIPBOARD_UNAVAILABLE');await navigator.clipboard.writeText(link)}catch{const area=document.createElement('textarea');area.value=link;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.focus();area.select();document.execCommand('copy');area.remove()}alert('لینک دعوت کپی شد ✓')};
 const patch=(delta:Partial<Room['settings']>)=>socket?.emit('settings:update',{...room.settings,...delta});

 if(room.state==='LOBBY')return <main><header><div className="logo">اسم‌فامیل</div><span className="status">● متصل</span></header><section className="layout"><div><div className="title"><div><span className="eyebrow">اتاق خصوصی</span><h1>همه آماده‌اند؟</h1></div>{host&&<button className="secondary" onClick={share}>کپی لینک دعوت 🔗</button>}</div><div className="players">{room.players.map((p,i)=><article key={p.id} className={p.ready?'ready':''}><span className="avatar">{['🦊','🐼','🦁','🐸','🐯','🐨','🦉','🐧'][i%8]}</span><div><b>{p.name} {p.host&&<em>میزبان</em>}</b><small>{p.connected?(p.ready?'آماده':'در انتظار'):'قطع ارتباط'}</small></div><i>{p.ready?'✓':'…'}</i></article>)}</div><button className="readyBtn" onClick={()=>socket?.emit('player:ready')}>{mine?.ready?'آماده نیستم':'آماده‌ام ✓'}</button></div><aside><h2>تنظیمات بازی</h2><label>زمان هر دور <select disabled={!host} value={room.settings.durationSeconds} onChange={e=>patch({durationSeconds:+e.target.value})}><option value="60">۱ دقیقه</option><option value="120">۲ دقیقه</option><option value="180">۳ دقیقه</option><option value="300">۵ دقیقه</option></select></label><label>تعداد دور <input disabled={!host} type="number" min="1" max="10" value={room.settings.roundCount} onChange={e=>patch({roundCount:Math.min(10,Math.max(1,+e.target.value||1))})}/></label><label>سطح دشواری <select disabled={!host} value={room.settings.difficulty} onChange={e=>patch({difficulty:e.target.value as any})}>{Object.entries(difficultyLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="switch"><input type="checkbox" disabled={!host} checked={room.settings.votingEnabled} onChange={e=>patch({votingEnabled:e.target.checked})}/> رأی‌گیری گروهی برای پاسخ‌های ناشناخته</label><h3>موضوعات ({room.settings.categoryIds.length}/۵ حداقل)</h3><div className="chips">{cats.map(c=><button key={c.id} disabled={!host} className={room.settings.categoryIds.includes(c.id)?'on':''} onClick={()=>{const ids=room.settings.categoryIds.includes(c.id)?room.settings.categoryIds.filter(x=>x!==c.id):[...room.settings.categoryIds,c.id];patch({categoryIds:ids})}}>{c.name}</button>)}</div>{host&&<button disabled={room.players.length<2||room.settings.categoryIds.length<5} onClick={()=>socket?.emit('game:start',null,(x:any)=>!x.ok&&alert(x.message))}>شروع بازی</button>}{!host&&<p className="notice">میزبان بازی را آغاز می‌کند.</p>}</aside></section></main>;

 if(room.state==='COUNTDOWN'){const seconds=Math.max(0,Math.ceil(((room.round?.startsAt??tick)-tick)/1000));return <main><header><div className="logo">اسم‌فامیل</div><span>دور {room.round?.number} از {room.settings.roundCount}</span></header><section className="game countdownWrap"><p className="eyebrow">حرف این دور</p><div className="letter"><strong>{room.round?.letter}</strong></div><div className="countdown">{seconds||'برو!'}</div><p>آماده شو…</p></section></main>}

 if(room.state==='VOTING'&&room.currentVote){const vote=room.currentVote,seconds=Math.max(0,Math.ceil((vote.endsAt-tick)/1000));const cast=(choice:'VALID'|'INVALID'|'UNSURE')=>socket?.emit('vote:cast',{voteSessionId:vote.id,choice},(x:any)=>x.ok&&setVoted(true));const owner=room.results?.players.find(p=>p.cells.some(c=>c.categoryId===vote.categoryId&&c.text===vote.text))?.playerId===me;return <main><header><div className="logo">رأی‌گیری پاسخ</div><span>{seconds} ثانیه</span></header><section className="center"><div className="card"><h1>آیا «{vote.text}» برای موضوع «{catName(vote.categoryId)}» درست است؟</h1>{owner?<p className="notice">این پاسخ متعلق به توست؛ رأی دیگران را ببین.</p>:<><button disabled={voted} onClick={()=>cast('VALID')}>درست است ✓</button><button disabled={voted} onClick={()=>cast('INVALID')}>غلط است ✕</button><button disabled={voted} className="secondary" onClick={()=>cast('UNSURE')}>مطمئن نیستم</button></>}{voted&&<p>رأی شما ثبت شد؛ نتیجه تا پایان زمان مخفی است.</p>}</div></section></main>}

 if((room.state==='RESULTS'||room.state==='FINISHED')&&room.results){const ranking=[...room.results.players].sort((a,b)=>b.totalScore-a.totalScore);const winner=room.state==='FINISHED'?ranking[0]:undefined;return <main><header><div className="logo">نتایج دور {room.round?.number}</div><span>{room.state==='FINISHED'?'پایان بازی':'امتیازها'}</span></header><section className="dashboard"><h1>{room.state==='FINISHED'?'جدول پایانی 🏆':'جدول نتایج'}</h1>{winner&&<p className="winner">🏆 برنده: <b>{winner.name}</b> با {winner.totalScore} امتیاز</p>}<div className="resultGrid">{ranking.map(player=><article className="card resultCard" key={player.playerId}><h2>{player.name} {room.results?.stopperId===player.playerId&&<em>متوقف‌کننده</em>}</h2><p><b>{player.roundScore}</b> امتیاز این دور · مجموع <b>{player.totalScore}</b></p>{player.cells.map(cell=><div className={`resultCell ${cell.status==='VALID'?'ok':cell.points<0?'bad':''}`} key={cell.categoryId}><span>{catName(cell.categoryId)}: <b>{cell.text||'—'}</b></span><small>{cell.reasonFa}</small><strong className={cell.points<0?'negative':''}>{cell.points>0?'+':''}{cell.points}</strong></div>)}</article>)}</div>{host&&room.state==='RESULTS'&&<button onClick={()=>socket?.emit('round:next',null,(x:any)=>!x.ok&&alert('ادامه ممکن نشد.'))}>{(room.round?.number??0)>=room.settings.roundCount?'اعلام نتیجه نهایی':'شروع دور بعد'}</button>}{room.state==='FINISHED'&&<button className="secondary" onClick={()=>location.href='/'}>بازگشت به خانه</button>}</section></main>}

 if(room.state==='VALIDATING'||room.state==='LOCKED')return <main><header><div className="logo">اسم‌فامیل</div><span>دور {room.round?.number}</span></header><section className="center"><div className="loader">⏳ در حال داوری پاسخ‌ها…</div></section></main>;

 const remain=Math.max(0,Math.ceil(((room.round?.endsAt??tick)-tick)/1000));const stopper=room.players.find(p=>p.id===room.round?.stopperId);const saveAnswer=(categoryId:string,text:string,immediate=false)=>{const timers=saveTimers.current;if(timers[categoryId])clearTimeout(timers[categoryId]);const send=()=>socket?.emit('answer:save',{roundId:room.round?.id,categoryId,text});if(immediate)send();else timers[categoryId]=setTimeout(send,300)};
 return <main><header><div className="logo">اسم‌فامیل</div><span>دور {room.round?.number} از {room.settings.roundCount}</span></header><section className="game"><div className="letter"><small>حرف این دور</small><strong>{room.round?.letter}</strong><span className={remain<=10?'urgent':''}>{Math.floor(remain/60)}:{String(remain%60).padStart(2,'0')}</span></div>{room.state==='STOP_CONFIRMATION'&&room.round?.stopperId!==me&&<div className="banner">✋ {stopper?.name??'یک بازیکن'} پایان دور را اعلام کرد — پاسخ‌ها در حال نهایی‌شدن‌اند.</div>}<div className="answers">{cats.filter(c=>room.settings.categoryIds.includes(c.id)).map(c=><label key={`${room.round?.id}-${c.id}`}>{c.name}<input disabled={room.state!=='PLAYING'&&room.state!=='STOP_CONFIRMATION'} defaultValue={mine?.answers[c.id]??''} onChange={e=>saveAnswer(c.id,e.target.value)} onBlur={e=>saveAnswer(c.id,e.target.value,true)} placeholder={`${c.name} با ${room.round?.letter}…`}/></label>)}</div>{room.state==='PLAYING'&&<button onClick={()=>socket?.emit('round:stop')}>پایان دور 🛎️</button>}{room.state==='STOP_CONFIRMATION'&&room.round?.stopperId===me&&<div className="modal"><div className="card"><h2>پاسخ‌ها را نهایی می‌کنی؟</h2><p>۱۰ ثانیه برای مرور پاسخ‌ها فرصت داری. اگر تأیید نکنی، بازی ادامه می‌یابد.</p><button onClick={()=>socket?.emit('round:confirm')}>تأیید و پایان دور</button></div></div>}</section></main>}

function Admin(){
 const[token,setToken]=useState(localStorage.adminToken??'');const[data,setData]=useState<any>();const[queue,setQueue]=useState<any[]>([]);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState('');
 const auth={authorization:`Bearer ${token}`};
 const load=()=>{Promise.all([request('/api/admin/dashboard',{headers:auth}),request('/api/admin/unknowns',{headers:auth})]).then(([d,q])=>{setData(d);setQueue(q as any[])}).catch(()=>setToken(''))};
 useEffect(()=>{if(token)load()},[token]);
 const decide=async(id:string,action:'APPROVE'|'REJECT')=>{setBusy(id);try{await request(`/api/admin/unknowns/${id}/decide`,{method:'POST',headers:auth,body:JSON.stringify({action})});load()}catch(e){alert((e as Error).message)}finally{setBusy('')}};
 if(!token)return <main className="center"><section className="card"><h1>ورود مدیر</h1><input placeholder="ایمیل" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="رمز عبور" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={async()=>{try{const x=await request('/api/admin/login',{method:'POST',body:JSON.stringify({email,password})});store('adminToken',(x as any).token);setToken((x as any).token)}catch(e){setError((e as Error).message)}}}>ورود امن</button>{error&&<p className="error">{error}</p>}</section></main>;
 const labels:any={terms:'واژه تأییدشده',aliases:'نام مستعار',rejected:'پاسخ ردشده',queue:'در انتظار بررسی',games:'بازی',rounds:'دور'};
 return <main><header><div className="logo">پنل مدیریت</div><button className="secondary" onClick={()=>{localStorage.removeItem('adminToken');setToken('')}}>خروج</button></header><section className="dashboard"><h1>نمای کلی فرهنگ بازی</h1><div className="stats">{Object.entries(data??{}).map(([k,v])=><article key={k}><b>{String(v)}</b><span>{labels[k]??k}</span></article>)}</div><h2>صف پاسخ‌های ناشناخته</h2>{!queue.length&&<p className="notice">هیچ پاسخ ناشناخته‌ای در انتظار بررسی نیست.</p>}<div className="queue">{queue.map(item=><article className="card queueItem" key={item.id}><div><b>{item.originalText}</b> <small>({item.category?.name})</small><div><small>حرف {item.letter} · {item.useCount} بار دیده‌شده · وضعیت {item.status}</small></div></div>{item.status==='PENDING'&&<div className="queueActions"><button disabled={busy===item.id} onClick={()=>decide(item.id,'APPROVE')}>تأیید و افزودن ✓</button><button disabled={busy===item.id} className="secondary" onClick={()=>decide(item.id,'REJECT')}>رد ✕</button></div>}</article>)}</div></section></main>}

function App(){const p=location.pathname.split('/').filter(Boolean);if(p[0]==='join'&&p[1])return <Join roomId={p[1]}/>;if(p[0]==='room'&&p[1])return <RoomPage roomId={p[1]}/>;if(p[0]==='admin')return <Admin/>;return <Home/>}
createRoot(document.getElementById('root')!).render(<App/>);
